/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: vendor/huawei/chipset_common/devkit/lcdkit/tools 
 *---------------------------------------------------------------------------*/

#ifndef _LCDKIT_EFFECT__H_
#define _LCDKIT_EFFECT__H_


#include "warsaw_va_tm_ft8716_5p2_1080p_video.h"

#include "warsaw_va_ebbg_nt35596s_5p2_1080p_video.h"

#include "warsaw_va_auo_td4310_5p2_1080p_video.h"

#include "warsaw_va_boe_td4300_5p2_1080p_video.h"

#include "default_auo_otm1901a_5p2_1080p_video_default.h"

/*---------------------------------------------------------------------------*/
/* static panel selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
WARSAW_VA_TM_FT8716_5P2_1080P_VIDEO_PANEL,
WARSAW_VA_EBBG_NT35596S_5P2_1080P_VIDEO_PANEL,
WARSAW_VA_AUO_TD4310_5P2_1080P_VIDEO_PANEL,
WARSAW_VA_BOE_TD4300_5P2_1080P_VIDEO_PANEL,
DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
INVALID_PANEL_ID,
};


/*---------------------------------------------------------------------------*/
/* static panel board mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct lcdkit_board_map {
    uint8_t lcd_id;
    uint8_t gpio_id;
    uint16_t board_id;
};

static struct lcdkit_board_map lcdkit_map[] = {
    {WARSAW_VA_TM_FT8716_5P2_1080P_VIDEO_PANEL, 0x01, 5000},
    {WARSAW_VA_EBBG_NT35596S_5P2_1080P_VIDEO_PANEL, 0x02, 5000},
    {WARSAW_VA_AUO_TD4310_5P2_1080P_VIDEO_PANEL, 0x06, 5000},
    {WARSAW_VA_BOE_TD4300_5P2_1080P_VIDEO_PANEL, 0x00, 5000},
    {DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, 0x0A, 0},
};

static void lcdkit_effect_get_data(uint8_t panel_id, struct hisi_panel_info* pinfo)
{
    switch (panel_id) {
    case WARSAW_VA_TM_FT8716_5P2_1080P_VIDEO_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = warsaw_va_tm_ft8716_5p2_1080p_video_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(warsaw_va_tm_ft8716_5p2_1080p_video_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = warsaw_va_tm_ft8716_5p2_1080p_video_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(warsaw_va_tm_ft8716_5p2_1080p_video_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = warsaw_va_tm_ft8716_5p2_1080p_video_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(warsaw_va_tm_ft8716_5p2_1080p_video_acm_lut_satr_table);
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = warsaw_va_tm_ft8716_5p2_1080p_video_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = warsaw_va_tm_ft8716_5p2_1080p_video_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = warsaw_va_tm_ft8716_5p2_1080p_video_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(warsaw_va_tm_ft8716_5p2_1080p_video_gamma_lut_table_R);
            pinfo->igm_lut_table_R = warsaw_va_tm_ft8716_5p2_1080p_video_igm_lut_table_R;
            pinfo->igm_lut_table_G = warsaw_va_tm_ft8716_5p2_1080p_video_igm_lut_table_G;
            pinfo->igm_lut_table_B = warsaw_va_tm_ft8716_5p2_1080p_video_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(warsaw_va_tm_ft8716_5p2_1080p_video_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &warsaw_va_tm_ft8716_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &warsaw_va_tm_ft8716_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(warsaw_va_tm_ft8716_5p2_1080p_video_gmp_lut_table_low32bit);
            pinfo->xcc_table = warsaw_va_tm_ft8716_5p2_1080p_video_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(warsaw_va_tm_ft8716_5p2_1080p_video_xcc_table);
        }
        break;
    case WARSAW_VA_EBBG_NT35596S_5P2_1080P_VIDEO_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = warsaw_va_ebbg_nt35596s_5p2_1080p_video_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(warsaw_va_ebbg_nt35596s_5p2_1080p_video_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = warsaw_va_ebbg_nt35596s_5p2_1080p_video_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(warsaw_va_ebbg_nt35596s_5p2_1080p_video_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = warsaw_va_ebbg_nt35596s_5p2_1080p_video_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(warsaw_va_ebbg_nt35596s_5p2_1080p_video_acm_lut_satr_table);
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = warsaw_va_ebbg_nt35596s_5p2_1080p_video_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = warsaw_va_ebbg_nt35596s_5p2_1080p_video_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = warsaw_va_ebbg_nt35596s_5p2_1080p_video_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(warsaw_va_ebbg_nt35596s_5p2_1080p_video_gamma_lut_table_R);
            pinfo->igm_lut_table_R = warsaw_va_ebbg_nt35596s_5p2_1080p_video_igm_lut_table_R;
            pinfo->igm_lut_table_G = warsaw_va_ebbg_nt35596s_5p2_1080p_video_igm_lut_table_G;
            pinfo->igm_lut_table_B = warsaw_va_ebbg_nt35596s_5p2_1080p_video_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(warsaw_va_ebbg_nt35596s_5p2_1080p_video_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &warsaw_va_ebbg_nt35596s_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &warsaw_va_ebbg_nt35596s_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(warsaw_va_ebbg_nt35596s_5p2_1080p_video_gmp_lut_table_low32bit);
            pinfo->xcc_table = warsaw_va_ebbg_nt35596s_5p2_1080p_video_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(warsaw_va_ebbg_nt35596s_5p2_1080p_video_xcc_table);
        }
        break;
    case WARSAW_VA_AUO_TD4310_5P2_1080P_VIDEO_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = warsaw_va_auo_td4310_5p2_1080p_video_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(warsaw_va_auo_td4310_5p2_1080p_video_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = warsaw_va_auo_td4310_5p2_1080p_video_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(warsaw_va_auo_td4310_5p2_1080p_video_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = warsaw_va_auo_td4310_5p2_1080p_video_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(warsaw_va_auo_td4310_5p2_1080p_video_acm_lut_satr_table);
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = warsaw_va_auo_td4310_5p2_1080p_video_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = warsaw_va_auo_td4310_5p2_1080p_video_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = warsaw_va_auo_td4310_5p2_1080p_video_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(warsaw_va_auo_td4310_5p2_1080p_video_gamma_lut_table_R);
            pinfo->igm_lut_table_R = warsaw_va_auo_td4310_5p2_1080p_video_igm_lut_table_R;
            pinfo->igm_lut_table_G = warsaw_va_auo_td4310_5p2_1080p_video_igm_lut_table_G;
            pinfo->igm_lut_table_B = warsaw_va_auo_td4310_5p2_1080p_video_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(warsaw_va_auo_td4310_5p2_1080p_video_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &warsaw_va_auo_td4310_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &warsaw_va_auo_td4310_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(warsaw_va_auo_td4310_5p2_1080p_video_gmp_lut_table_low32bit);
            pinfo->xcc_table = warsaw_va_auo_td4310_5p2_1080p_video_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(warsaw_va_auo_td4310_5p2_1080p_video_xcc_table);
        }
        break;
    case WARSAW_VA_BOE_TD4300_5P2_1080P_VIDEO_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = warsaw_va_boe_td4300_5p2_1080p_video_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(warsaw_va_boe_td4300_5p2_1080p_video_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = warsaw_va_boe_td4300_5p2_1080p_video_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(warsaw_va_boe_td4300_5p2_1080p_video_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = warsaw_va_boe_td4300_5p2_1080p_video_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(warsaw_va_boe_td4300_5p2_1080p_video_acm_lut_satr_table);
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = warsaw_va_boe_td4300_5p2_1080p_video_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = warsaw_va_boe_td4300_5p2_1080p_video_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = warsaw_va_boe_td4300_5p2_1080p_video_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(warsaw_va_boe_td4300_5p2_1080p_video_gamma_lut_table_R);
            pinfo->igm_lut_table_R = warsaw_va_boe_td4300_5p2_1080p_video_igm_lut_table_R;
            pinfo->igm_lut_table_G = warsaw_va_boe_td4300_5p2_1080p_video_igm_lut_table_G;
            pinfo->igm_lut_table_B = warsaw_va_boe_td4300_5p2_1080p_video_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(warsaw_va_boe_td4300_5p2_1080p_video_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &warsaw_va_boe_td4300_5p2_1080p_video_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &warsaw_va_boe_td4300_5p2_1080p_video_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(warsaw_va_boe_td4300_5p2_1080p_video_gmp_lut_table_low32bit);
            pinfo->xcc_table = warsaw_va_boe_td4300_5p2_1080p_video_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(warsaw_va_boe_td4300_5p2_1080p_video_xcc_table);
        }
        break;
    case DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL:
        if (pinfo->acm_support == 1)
        {
            pinfo->acm_lut_hue_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_hue_table;
            pinfo->acm_lut_hue_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_hue_table);
            pinfo->acm_lut_sata_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_sata_table;
            pinfo->acm_lut_sata_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_sata_table);
            pinfo->acm_lut_satr_table = default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr_table;
            pinfo->acm_lut_satr_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_acm_lut_satr_table);
        }
        if (pinfo->gamma_support == 1)
        {
            pinfo->gamma_lut_table_R = default_auo_otm1901a_5p2_1080p_video_default_gamma_lut_table_R;
            pinfo->gamma_lut_table_G = default_auo_otm1901a_5p2_1080p_video_default_gamma_lut_table_G;
            pinfo->gamma_lut_table_B = default_auo_otm1901a_5p2_1080p_video_default_gamma_lut_table_B;
            pinfo->gamma_lut_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_gamma_lut_table_R);
            pinfo->igm_lut_table_R = default_auo_otm1901a_5p2_1080p_video_default_igm_lut_table_R;
            pinfo->igm_lut_table_G = default_auo_otm1901a_5p2_1080p_video_default_igm_lut_table_G;
            pinfo->igm_lut_table_B = default_auo_otm1901a_5p2_1080p_video_default_igm_lut_table_B;
            pinfo->igm_lut_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_igm_lut_table_R);
            pinfo->gmp_lut_table_low32bit = &default_auo_otm1901a_5p2_1080p_video_default_gmp_lut_table_low32bit[0][0][0];
            pinfo->gmp_lut_table_high4bit = &default_auo_otm1901a_5p2_1080p_video_default_gmp_lut_table_high4bit[0][0][0];
            pinfo->gmp_lut_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_gmp_lut_table_low32bit);
            pinfo->xcc_table = default_auo_otm1901a_5p2_1080p_video_default_xcc_table;
            pinfo->xcc_table_len = ARRAY_SIZE(default_auo_otm1901a_5p2_1080p_video_default_xcc_table);
        }
        break;
    default:
        HISI_FB_INFO("Panel ID not detected %d\n", panel_id);
        break;
    }
}

static uint8_t lcdkit_panel_init(uint32_t lcdkit_id, uint32_t product_id)
{
    uint8_t lcd_panel_id = DEFAULT_AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL;
    int i = 0;
    for (i = 0; i < ARRAY_SIZE(lcdkit_map); ++i) {
      if ((lcdkit_map[i].board_id == product_id) && (lcdkit_map[i].gpio_id == lcdkit_id)){
            lcd_panel_id = lcdkit_map[i].lcd_id;
            break;
        }
    }

    return lcd_panel_id;
}


#endif /*_LCDKIT_EFFECT__H_*/
