# Makefile for the irda drivers.
#

# Each configuration option enables a list of files.

#obj-$(CONFIG_CYPRESS_TS_KIT)  += cypress/
obj-$(CONFIG_FOCAL_TS_KIT)  += focaltech/
obj-$(CONFIG_SYNAPTICS_TS_KIT)  += synaptics/
obj-$(CONFIG_PARADE_TS_KIT)  += parade/
obj-$(CONFIG_NOVATEK_TS_KIT)  += novatek/
obj-$(CONFIG_ILITEK_TS_KIT)  += ilitek/
#ifeq ($(CONFIG_HUAWEI_TS_TEST),y)
#EXTRA_CFLAGS += -DHUAWEI_TOUCHSCREEN_TEST
#endif
#EXTRA_CFLAGS += -Idrivers/hisi/tzdriver