# lcdkit-dtsi-parser.pl



my $paranum = 0;
my $platform = $ARGV[$paranum];
$paranum++;

if ($platform eq 'qcom')
{
    require "./lcdkit-base-lib.pl";
}
else
{
    require "../../../../../chipset_common/devkit/lcdkit/lcdkit_tool/lcdkit-base-lib.pl";
}

# initialize the parser
my $lcd_xml_parser = new XML::LibXML;
my $parse_error_string = get_err_string();

debug_print("get chip platform is : $platform\n");
my $out_dtsi_file = $ARGV[$paranum];
$paranum++;
debug_print("get dtsi file path is : $out_dtsi_file\n");

my $xml_file_num = uc($ARGV[$paranum]);
$paranum++;
debug_print("get xml file number is $xml_file_num\n");

if(scalar @ARGV < ($xml_file_num + $paranum))
{
    error_print(($xml_file_num + $paranum) . " command line arguments required.\n");
    error_print("1-chip platform(hisi or qcom)\n");
    error_print("2-out file path of dtsi file\n");
    error_print("3-the number of XML Document to be parsed\n");
    error_print("4-". ($xml_file_num + $paranum) . ":XML Documents to parse\n");

    exit 1;
}

my @lcd_xml_doc;
my @lcd_xml_files;
for (my $count = 0; $count < $xml_file_num; $count++) {
    debug_print("get para file [$count] is $ARGV[$count + $paranum]\n");
    push(@lcd_xml_files, $ARGV[$count + $paranum]);
    push(@lcd_xml_doc, $lcd_xml_parser->parse_file($ARGV[$count + $paranum]));
}

my $panel_file_name = file_name_from_path($out_dtsi_file);
welcome_print_begin(\@lcd_xml_files, $panel_file_name);

my $xml_version = parse_multi_xml('/hwlcd/Version');
if ($xml_version eq $parse_error_string) {
    error_print("get error xml file version!\n");
    exit_with_info($panel_file_name, 1);
}
debug_print("xml file version is : $xml_version\n");

print "=====================parsing dtsi file: $panel_file_name.dtsi ======================\n";

#generater dtsi file used in kernel
open (my $panel_dtsi_file, '>'.$out_dtsi_file) or die "fail to open file $out_dtsi_file\n";

print $panel_dtsi_file create_dtsi_header($panel_file_name, $xml_version);

#add entry if need, and please keep alignment, thanks!
my @dtsi_property_strings = (
        # the parameter of lcd device 
        ['/hwlcd/PanelEntry/PanelCompatible',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\tcompatible = ",                                ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelName',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-name = ",                      ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelType',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-type = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelXres',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-xres = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelYres',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-yres = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelWidth',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-width = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelHeight',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-height = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelOnCommand',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-on-command = ",                ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelOnCommandState',           \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-on-command-state = \"",        "\";\n"               ],
         ['/hwlcd/PanelEntry/PanelDisplayOnCommand',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-display-on-command = ",                ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelOffCommand',               \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-off-command = ",               ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelOffCommandState',          \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-off-command-state = \"",       "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelBacklightCommand',         \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-backlight-command = ",         ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelBacklightCommandState',    \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-backlight-command-state = \"", "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCabcOffMode',              \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-cabc-off-command = ",          ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcOffModeState',         \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-cabc-off-command-state = \"",  "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCabcUiMode',               \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-cabc-ui-command = ",           ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcUiModeState',          \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-cabc-ui-command-state = \"",   "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCabcStillMode',            \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-cabc-still-command = ",        ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcStillModeState',       \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-cabc-still-command-state = \"","\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCabcMovingMode',           \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-cabc-moving-command = ",       ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCabcMovingModeState',      \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-cabc-moving-command-state = \"","\";\n"              ],
        ['/hwlcd/PanelEntry/PanelCabcSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-cabc-support = <",             ">;\n"                ],

       ['/hwlcd/PanelEntry/PanelDisplayOnEffectCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-display-on-effect-command = ",  ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDisplayOnEffectSupport',    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-display-on-effect-support = <", ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelCeOffMode',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-ce-off-command = ",            ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCeSrgbMode',               \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-ce-srgb-command = ",           ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCeUserMode',               \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-ce-user-command = ",           ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCeVividMode',              \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-ce-vivid-command = ",          ";\n"                 ],
        ['/hwlcd/PanelEntry/CeSupport',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-ce-support = <",               ">;\n"                ],

        ['/hwlcd/PanelEntry/PanelDotInversionCommand' ,     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dot-inversion-command = ",     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDotInversionCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dot-inversion-command-state = \"",      "\";\n"      ],
        ['/hwlcd/PanelEntry/PanelColumnInversionCommand',   \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-column-inversion-command = ",  ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelColumnInversionCommandState',   \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-column-inversion-command-state = \"",   "\";\n"      ],
        ['/hwlcd/PanelEntry/PanelInversionSupport',         \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-inversion-support = <",        ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelForwordScanCommand',       \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-forword-scan-command = ",      ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelForwordScanCommandState',  \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-forword-scan-command-state = \"",       "\";\n"      ],
        ['/hwlcd/PanelEntry/PanelRevertScanCommand',        \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-revert-scan-command = ",       ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelRevertScanCommandState',   \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-revert-scan-command-state = \"", "\";\n"             ],
        ['/hwlcd/PanelEntry/PanelScanSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-scan-support = <",             ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelDisplayRegionCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-display-region-command = ",    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDisplayRegionCommandState',\&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-display-region-command-state = \"",  "\";\n"         ],
        ['/hwlcd/PanelEntry/PanelDisplayRegionSupport',     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-display-region-support = <",   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelChecksumEnterCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-checksum-enter-command = ",    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelChecksumEnterCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-checksum-enter-command-state = \"",  "\";\n"         ],
        ['/hwlcd/PanelEntry/PanelChecksumCommand',          \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-checksum-command = ",          ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelChecksumCommandState',     \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-checksum-command-state = \"",  "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelChecksumExitCommand',      \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-checksum-exit-command = ",     ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelChecksumExitCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-checksum-exit-command-state = \"",  "\";\n"          ],
        ['/hwlcd/PanelEntry/PanelChecksumValue',            \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-checksum-value = ",            ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelChecksumSupport',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-checksum-support = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelEsdRegCommand',            \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-esd-reg-command = ",           ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelEsdRegCommandState',       \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-esd-reg-command-state = \"",   "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelEsdValue',                 \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-esd-value = ",                 ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelEsdSupport',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-esd-support = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelCheckRegCommand',          \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-check-reg-command = ",         ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCheckRegValue',            \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-check-reg-value = ",           ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCheckRegCommandState',     \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-check-reg-command-state = \"", "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelCheckRegSupport',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-check-reg-support = <",        ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelMipiDetectCommand',        \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-mipi-detect-command = ",       ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelMipiDetectValue',          \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-mipi-detect-value = ",         ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelMipiDetectMask',           \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-mipi-detect-mask = ",          ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelMipiDetectCommandState',   \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-mipi-detect-command-state = \"",     "\";\n"         ],
        ['/hwlcd/PanelEntry/PanelMipiDetectSupport',        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-mipi-detect-support = <",      ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckCommand',  \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-command = ", ";\n"                ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-command-state = \"", "\";\n"      ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckEnterCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-enter-command = ", ";\n"          ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckEnterCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-enter-command-state = \"", "\";\n"],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckExitCommand',   \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-exit-command = ",    ";\n"        ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckExitCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-exit-command-state = \"", "\";\n" ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckEnableCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-enable-command = ",      ";\n"    ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckDisableCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-disable-command-state = \"", "\";\n"  ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckValue',    \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-value = ",  ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDynamicSramCheckSupport',  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-dynamic-sram-check-support = <", ">;\n"              ],
        ['/hwlcd/PanelEntry/PanelFpsToThirtyCommand',           \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-fps-to-thirty-command = ",         ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelFpsToThirtyCommandState',      \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-fps-to-thirty-command-state = \"", "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelFpsToSixtyCommand',           \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-fps-to-sixty-command = ",         ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelFpsToSixtyCommandState',      \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-fps-to-sixty-command-state = \"", "\";\n"               ],
        ['/hwlcd/PanelEntry/PanelFpsToThirtyValue',           \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-fps-to-thirty-value = ",         ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelFpsToSixtyValue',      \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-fps-to-sixty-value = ",   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDfrEnableCommand',         \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dfr-enable-command = ",        ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDfrEnableCommandState',    \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dfr-enable-command-state = \"", "\";\n"              ],
        ['/hwlcd/PanelEntry/PanelDfrDisableCommand',        \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dfr-disable-command = ",       ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelDfrDisableCommandState',   \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-dfr-disable-command-state = \"", "\";\n"             ],
        ['/hwlcd/PanelEntry/PanelFpsUpdtSupport',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-fps-updt-support = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelFpsFuncSwitch',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-fps-func-switch = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelLpTohsMipiCheckWriteCommand',        \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lptohs-mipi-check-write-command = ", ";\n"           ],
        ['/hwlcd/PanelEntry/PanelLpTohsMipiCheckWriteCommandState',        \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lptohs-mipi-check-write-command-state = \"", "\";\n" ],
        ['/hwlcd/PanelEntry/PanelLpTohsMipiCheckReadCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lptohs-mipi-check-read-command = ", ";\n"            ],
        ['/hwlcd/PanelEntry/PanelLpTohsMipiCheckReadCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lptohs-mipi-check-read-command-state = \"", "\";\n"  ],
        ['/hwlcd/PanelEntry/PanelLpTohsMipiCheckValue',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lptohs-mipi-check-value = ",   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelLpTohsMipiCheckMask',      \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lptohs-mipi-check-mask = ",    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelLpTohsMipiCheckSupport',   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-lptohs-mipi-check-support = <", ">;\n"               ],
        ['/hwlcd/PanelEntry/PanelAclEnableCommand',         \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-acl-enable-command = ",        ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelAclEnableCommandState',    \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-acl-enable-command-state = \"", "\";\n"              ],
        ['/hwlcd/PanelEntry/PanelAclCtrlSupport',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-acl-ctrl-support = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelHbmEnableCommand',         \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-hbm-enable-command = ",        ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelHbmEnableCommandState',    \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-hbm-enable-command-state = \"", "\";\n"              ],
        ['/hwlcd/PanelEntry/PanelHbmCtrlSupport',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-hbm-ctrl-support = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelVrModeEnableCommand',      \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-vr-mode-enable-command = ",    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelVrModeEnableCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-vr-mode-enable-command-state = \"", "\";\n"          ],
        ['/hwlcd/PanelEntry/PanelVrModeDisableCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-vr-mode-disable-command = ",   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelVrModedisableCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-vr-mode-disable-command-state = \"", "\";\n"         ],
        ['/hwlcd/PanelEntry/PanelVrSupport',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-vr-support = <",               ">;\n"                ],
        
        ['/hwlcd/PanelEntry/PanelCurrentDetectEnterCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-current-detect-enter-command = ", ";\n"              ],
        ['/hwlcd/PanelEntry/PanelCurrentDetectEnterCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-current-detect-enter-command-state = \"", "\";\n"    ],
        ['/hwlcd/PanelEntry/PanelCurrentDetectExitCommand', \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-current-detect-exit-command = ", ";\n"               ],
        ['/hwlcd/PanelEntry/PanelCurrentDetectExitCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-current-detect-exit-command-state = \"", "\";\n"     ],
        ['/hwlcd/PanelEntry/PanelCurrentDetectCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-current-detect-command = ",    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelCurrentDetectSupport',     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-current-detect-support = <",   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelCurrentMask',                \&parse_multi_xml,
        \&parser_hex_order,                                "-f",        'comm',
        "\t\thw,lcdkit-panel-current-mask =  ",              ";\n"       ],
        ['/hwlcd/PanelEntry/PanelLvDetectEnterCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lv-detect-enter-command = ",   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelLvDetectEnterCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-Lv-detect-enter-command-state = \"", "\";\n"         ],
        ['/hwlcd/PanelEntry/PanelLvDetectExitCommand',      \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lv-detect-exit-command = ",    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelLvDetectExitCommandState', \&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lv-detect-exit-command-state = \"", "\";\n"          ],
        ['/hwlcd/PanelEntry/PanelLvDetectCommand',          \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-lv-detect-command = ",         ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelLvDetectSupport',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-lv-detect-support = <",        ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelShutdownSleepSupport',     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-shutdown-sleep-support = <",   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelShutdownSleepCommand',     \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-shutdown-sleep_command = ",    ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelShutdownSleepCommandState',\&parse_multi_xml,
        \&parser_cmd_state,                                 "-f",        'comm',
        "\t\thw,lcdkit-panel-shutdown-sleep_command-state = \"",  "\";\n"         ],

        #the parameter of Qcom platform
        ['/hwlcd/PanelEntry/ColorFormat',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-dsi-bpp = <",                        ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelCmdType',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-panel-cmd-type = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/PixelPacking',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-pixel-packing = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/UnderFlowColor',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-underflow-color = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/BorderColor',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-border-color = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelOrientation',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-panel-orientation = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/BLMaxLevel',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-brightness-max-level = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/BLMinLevel',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-bl-min-level = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/BLMaxLevel',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-bl-max-level = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/InterleaveMode',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-interleave-mode = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/TECheckEnable',                 \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-te-check-enable;\n",                 ""                    ],
        ['/hwlcd/PanelEntry/LcdSleepResetEnable',           \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-down-reset-enable;\n",               ""                    ],
       #['/hwlcd/PanelEntry/TpPreLcdEnable',                \&parse_multi_xml,
       #"1",                                                "eq",        'qcom',
       #"\t\thw,lcdkit-tp-pre-lcd-enable;\n",               ""                    ],
        ['/hwlcd/PanelEntry/TEUsingTEPin',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-te-using-te-pin;\n",                 ""                    ],
        ['/hwlcd/PanelEntry/HSyncPulse',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-h-sync-pulse = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/HFPPowerMode',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-hfp-power-mode = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/HSAPowerMode',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-hsa-power-mode = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/HBPPowerMode',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-hbp-power-mode = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/LastLineInterleave',            \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-last-line-interleave = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/BLLPPowerMode',                 \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-bllp-power-mode;\n",                 ""                    ],
        ['/hwlcd/PanelEntry/BLLPEOFPowerMode',              \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-bllp-eof-power-mode;\n",             ""                    ],
        ['/hwlcd/PanelEntry/TrafficMode',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-traffic-mode = ",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/TEDCSCommand',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-te-dcs-command = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/WrMemContinue',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-wr-mem-continue = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/WrMemStart',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-wr-mem-start = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/TEPinSelect',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-te-pin-select = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/DSIVirtualChannelId',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-virtual-channel-id = <",             ">;\n"                ],
        ['/hwlcd/PanelEntry/ColorOrder',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-color-order = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/Lane0State',                    \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-lane-0-state;\n",                    ""                    ],
        ['/hwlcd/PanelEntry/Lane1State',                    \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-lane-1-state;\n",                    ""                    ],
        ['/hwlcd/PanelEntry/Lane2State',                    \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-lane-2-state;\n",                    ""                    ],
        ['/hwlcd/PanelEntry/Lane3State',                    \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-lane-3-state;\n",                    ""                    ],
        ['/hwlcd/PanelEntry/HLeftBorder',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-h-left-border = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/HRightBorder',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-h-right-border = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/VTopBorder',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-v-top-border = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/VBottomBorder',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-v-bottom-border = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelFrameRate',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-panel-framerate = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelClockrate',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-panel-clockrate = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelTimings',                  \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'qcom',
        "\t\thw,lcdkit-panel-timings = ",                   ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelTimingsV2',                \&parse_multi_xml,
        \&parser_hex_order,                                 "-f",        'qcom',
        "\t\thw,lcdkit-panel-timings-phy-v2 = ",            ";\n"                 ],
        ['/hwlcd/PanelEntry/TClkPre',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-t-clk-pre = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/TClkPost',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-t-clk-post = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/RxEotIgnore',                   \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-rx-eot-ignore = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/TxEotAppend',                   \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-tx-eot-append",                      ";\n"                 ],
        ['/hwlcd/PanelEntry/DSIStream',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-stream = <",                         ">;\n"                ],
        ['/hwlcd/PanelEntry/ModSelGpioState',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-mode-sel-gpio-state = <",            ">;\n"                ],
        ['/hwlcd/PanelEntry/TransferTimeUs',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-mdp-transfer-time-us = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/Lp11InitFlag',                  \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-lp11-init;\n",                       ""                    ],
       #['/hwlcd/PanelEntry/PanelInitDelay',                \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'qcom',
       #"\t\thw,lcdkit-init-delay-us = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/PostInitDelay',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-post-init-delay = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/DSIMDPTrigger',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-mdp-trigger = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/DSIDMATrigger',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-dma-trigger = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/AdjTimerWakeupMs',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-adjust-timer-wakeup-ms = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/ForceClkLaneHs',                \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-force-clock-lane-hs",                ";\n"                 ],
        ['/hwlcd/PanelEntry/LcdDbaPanel',                   \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\thw,lcdkit-dba-panel",                          ";\n"                 ],
        ['/hwlcd/PanelEntry/LcdBridgeName',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-bridge-name = ",                     ";\n"                 ],
        ['/hwlcd/PanelEntry/BLPMICControlType',             \&parse_multi_xml,
        \&parser_pmic_ctrl,                                 "-f",        'qcom',
        "\t\thw,lcdkit-bl-pmic-control-type = \"",          "\";\n"               ],
        ['/hwlcd/PanelEntry/SupplyEntries',                 \&parse_multi_xml,
        \&apply_patten,                                     "-f",        'qcom',
        "\t\tqcom,panel-supply-entries = <&",               ">;\n"                ],
        ['/hwlcd/PanelEntry/DSILaneMap',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-lane-map = ",                        ";\n"                 ],
        ['/hwlcd/PanelEntry/DelayBeBL',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-delay-before-bl = <",                ">;\n"                ],

        ['/hwlcd/PanelEntry/PanelOffResetHigh',             \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tqcom,ulps-enabled",                            ";\n"                 ],
        ['/hwlcd/PanelEntry/PanelOffResetHigh',             \&parse_multi_xml,
        "1",                                                "eq",        'qcom',
        "\t\tqcom,suspend-ulps-enabled",                    ";\n"                 ],
        ['/hwlcd/PanelEntry/GpioBlEn',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'qcom',
        "\t\thw,lcdkit-bl-en-gpio = <",                     ">;\n"                ],

       #['/hwlcd/PanelEntry/RoiAlignment',                  \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'qcom',
       #"\t\thw,lcdkit-panel-roi-alignment = <",            ">;\n"                ],
       #['/hwlcd/PanelEntry/DsiCompression',                \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'qcom',
       #"\t\thw,lcdkit-Compression = <",                    ">;\n"                ],
       #['/hwlcd/PanelEntry/PostOnCommand',                 \&parse_multi_xml,
       #\&parser_hex_order,                                 "-f",        'qcom',
       #"\t\thw,lcdkit-post-on-command = ",                 ";\n"                 ],
       #['/hwlcd/PanelEntry/PanelController',               \&parse_multi_xml,
       #\&apply_patten,                                     "-f",        'qcom',
       #"\t\thw,lcdkit-panel-controller = <&",              ">;\n"                ],
       #['/hwlcd/PanelEntry/PanelDestination',              \&parse_multi_xml,
       #\&parser_small_trans,                               "-f",        'qcom',
       #"\t\thw,lcdkit-panel-destination = ",               ";\n"                 ],
       #['/hwlcd/PanelEntry/TEvSyncRdPtrIrqLine',           \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'qcom',
       #"\t\thw,lcdkit-te-v-sync-rd-ptr-irq-line = <",      ">;\n"                ],

        #the parameter of hisi platform
        ['/hwlcd/PanelEntry/PanelOrientation',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-orientation = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBpp',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-bpp = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBgrfmt',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-bgrfmt = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBlType' ,                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-bl-type = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBlmin' ,                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-blmin = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBlmax',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-blmax = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBlDef',                    \&parse_multi_xml,      
        'need_nothing_here',                                "-n",        'hisi',     
        "\t\thw,lcdkit-panel-bl-def = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBlMaxnit',                    \&parse_multi_xml,      
        'need_nothing_here',                                "-n",        'hisi',     
        "\t\thw,lcdkit-panel-bl-maxnit = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelCmdType',                  \&parse_multi_xml,       
        'need_nothing_here',                                "-n",        'hisi',   
        "\t\thw,lcdkit-panel-cmd-type = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelIfbcType',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-ifbctype = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelFrcEnable',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-frc-enable = <",               ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelEsdSkipMipiCheck',         \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-esd-skip-mipi-check = <",      ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelPxlClk',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-pxl-clk = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelPxlClkDiv',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-pxl-clk-div = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelTpResumeNosync',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-tp-resume-nosync = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelDisplayOnInBaklight',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-display-on-in-backlight = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelDirtUpdtSupport',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-dirt-updt-support = <",        ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelDsiUptSupport',            \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-dsi-upt-support = <",          ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelVsynCtrType',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-vsyn-ctr-type = <",            ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBlPwmPreciType',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-bl-pwm-preci-type = <",        ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelBlIcCtrlType',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-bl-ic-ctrl-type = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelFpsUpdtOnly',              \&parse_multi_xml,
        'need_nothing_here',                                 "-n",        'hisi',
        "\t\thw,lcdkit-panel-fps-updt-only = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelStepSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-step-support = <",             ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelXccSetInIsrSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-xcc-set-in-isr-support = <",             ">;\n"                ],
        ['/hwlcd/PanelEntry/LdiHsyncPlr',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-ldi-hsync-plr = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/LdiVsyncPlr',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-ldi-vsync-plr = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/LdiPixelClkPlr',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-ldi-pixel-clk-plr = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/LdiDataEnPlr',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-ldi-data-en-plr = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/LdiDpiAOverlapSize',            \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-ldi-dpi-a-overlap-size = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/LdiDpiBOverlapSize',            \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-ldi-dpi-b-overlap-size = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/SblStrenLimit',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-stren-limit = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/SblCalA',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-cal-a = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/SblCalB',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-cal-b = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/SblCalC',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-cal-c = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/SblCalD',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-cal-d = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/SblTfCtl',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-tf-ctl = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/SblBlmin',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-bl-min = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/SblBlmax',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-bl-max = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/SblBlScale',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-bl-scale = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/SblAmLightMin',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-am-light-min = <",               ">;\n"                ],
        ['/hwlcd/PanelEntry/SblFilterA',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-filter-a = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/SblFilterB',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-filter-b = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/SblLogoLeft',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-logo-left = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/SblLogoTop',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-logo-top = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/SblVarianceIntensitySpace',     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-variance-intensity-space = <",   ">;\n"                ],
        ['/hwlcd/PanelEntry/SblSlopeMax',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-slope-max = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/SblSlopeMin',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-slope-min = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiLaneNums',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-lane-nums = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiColorMode',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-color-mode = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiVc',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-vc = <",                        ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiDsiBitClk',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-dsi-bit-clk = <",               ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiBurstMode',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-burst-mode = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiMaxEscClk',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-max-esc-clk = <",               ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValA',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-dsi-bit-clk-val-a = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValB',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-dsi-bit-clk-val-b = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValC',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-dsi-bit-clk-val-c = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValD',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-dsi-bit-clk-val-d = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkValE',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-dsi-bit-clk-val-e = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiDsiBitClkUpt',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-dsi-bit-clk-upt = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiRgVcmAdjust',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-rg-vcm-adjust = <",             ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiNonContinueEnable',         \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-non-continue-enable = <",       ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiClkPostAdjust',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-clk-post-adjust = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiClkPreAdjust',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-clk-pre-adjust = <",            ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiClkTHsPrepareAdjust',       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-clk-t-hs-prepare-adjust = <",   ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiClkTLpxAdjust',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-clk-t-lpx-adjust = <",          ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiClkTHsTrailAdjust',         \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-clk-t-hs-trail-adjust = <",     ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiClkTHsExitAdjust',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-clk-t-hs-exit-adjust = <",      ">;\n"                ],
        ['/hwlcd/PanelEntry/MipiClkTHsZeroAdjust',          \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-mipi-clk-t-hs-zero-adjust = <",      ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtLeftAlign',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-left-align = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtRightAlign',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-right-align = <",               ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtTopAlign',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-top-align = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtBottAlign',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-bott-align = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtWidthAlign',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-width-align = <",               ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtHeightAlign',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-height-align = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtWidthMin',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-width-min = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtHeightMin',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-height-min = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtTopStart',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-top-start = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/DirtBottStart',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-dirt-bott-start = <",                ">;\n"                ],
        ['/hwlcd/PanelEntry/Gpios',                         \&parse_multi_xml,
        \&parse_gpios,                                      "-f",        'hisi',
        "\t\thw,lcdkit-gpios = ",                           ";\n"                 ],
        ['/hwlcd/PanelEntry/LcdBlSupply',                   \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tlcd_backlight-supply = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdBiasSupply',                 \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tvcc_lcdbias-supply = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdVspSupply',                  \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tlcd_vsp-supply = <",                           ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdVsnSupply',                  \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tlcd_vsn-supply = <",                           ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdIOVcc',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tlcdio-vcc-supply = <",                         ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdANVcc',                      \&parse_multi_xml,
        \&add_get_addr,                                     "-f",        'hisi',
        "\t\tlcdanalog-vcc-supply = <",                     ">;\n"                ],
	
        ['/hwlcd/PanelEntry/LcdPinMuxA',                    \&parse_multi_xml,
        \&pin_func_trans,                                   "-f",        'hisi',
        "\t\tpinctrl-0 = <",                                ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdPinMuxB',                    \&parse_multi_xml,
        \&pin_func_trans,                                   "-f",        'hisi',
        "\t\tpinctrl-1 = <",                                ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdPinNames',                   \&parse_multi_xml,
        \&pin_name_trans,                                   "-f",        'hisi',
        "\t\tpinctrl-names = ",                             ";\n"                 ],
        ['/hwlcd/PanelEntry/Status',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\tstatus = ",                                    ";\n"                 ],
        ['/hwlcd/PanelEntry/SblSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-sbl-support = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/GammaSupport',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-gamma-support = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/GmpSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-gmp-support = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/ColorTempSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-color-temp-support = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/ComformModeSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-comform-mode-support = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/CinemaModeSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-cinema-mode-support = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/PrefixSharpTwoDSupport',        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-prefix-sharp-two-d-support = <",     ">;\n"                ],
        ['/hwlcd/PanelEntry/XccSupport',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-xcc-support = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/PrefixCeSupport',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-prefix-ce-support = <",              ">;\n"                ],
        ['/hwlcd/PanelEntry/PrefixSharpOneDSupport',        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-prefix-sharp-one-d-support = <",     ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/AcmSupport',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-acm-support = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/AcmCeSupport',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-acm-ce-support = <",                 ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/AcmValidNum',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-acm-valid-num = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_hh0',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_hh0 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_lh0',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_lh0 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_hh1',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_hh1 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_lh1',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_lh1 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_hh2',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_hh2 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_lh2',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_lh2 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_hh3',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_hh3 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_lh3',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_lh3 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_hh4',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_hh4 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_lh4',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_lh4 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_hh5',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_hh5 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_lh5',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_lh5 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_hh6',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_hh6 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/acm/r_lh6',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-r_lh6 = <",                          ">;\n"                ],
        ['/hwlcd/PanelEntry/ColorTempRectifyR',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-color-temp-rectify-r = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/ColorTempRectifyG',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-color-temp-rectify-g = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/ColorTempRectifyB',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-color-temp-rectify-b = <",           ">;\n"                ],

        ['/hwlcd/PanelEntry/HiaceSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-hiace-support = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelEffectSupport',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-panel-effect-support = <",                  ">;\n"         ],
        ['/hwlcd/PanelEntry/Arsr1pSharpnessSupport',        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-arsr1p-sharpness-support = <",              ">;\n"         ],

        ['/hwlcd/PanelEntry/IGlobalHistBlackPos',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-iglobal-hist-black-pos = <",                ">;\n"         ],
        ['/hwlcd/PanelEntry/IGlobalHistWhitePos',           \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-iglobal-hist-white-pos = <",                ">;\n"         ],
        ['/hwlcd/PanelEntry/IGlobalHistBlackWeight',        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-iglobal-hist-black-weight = <",             ">;\n"         ],
        ['/hwlcd/PanelEntry/IGlobalHistWhiteWeight',        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-iglobal-hist-white-weight = <",             ">;\n"         ],
        ['/hwlcd/PanelEntry/IGlobalHistZeroCutRatio',       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-iglobal-hist-zero-cut-ratio = <",           ">;\n"         ],
        ['/hwlcd/PanelEntry/IGlobalHistSlopeCutRatio',        \&parse_multi_xml,
        'need_nothing_here',                                 "-n",        'hisi',
        "\t\thw,lcdkit-iglobal-hist-slope-cut-ratio = <",          ">;\n"         ],
        ['/hwlcd/PanelEntry/IMaxLcdLuminance',               \&parse_multi_xml,
        'need_nothing_here',                                 "-n",        'hisi',
        "\t\thw,lcdkit-imax-lcd-luminance = <",                    ">;\n"         ],
        ['/hwlcd/PanelEntry/IMinLcdLuminance',               \&parse_multi_xml,
        'need_nothing_here',                                 "-n",        'hisi',
        "\t\thw,lcdkit-imin-lcd-luminance = <",              ">;\n"               ],
        ['/hwlcd/PanelEntry/CfgName',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'hisi',
        "\t\thw,lcdkit-cfg-name = ",                         ";\n"                ],
        ['/hwlcd/PanelEntry/EffectSupportMode',               \&parse_multi_xml,
        'need_nothing_here',                                 "-n",        'hisi',
        "\t\thw,lcdkit-effect-support-mode = <",              ">;\n"               ],
       #['/hwlcd/PanelEntry/AcmLutHueTable',                \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-acm-lut-hue-table = <",              ">;\n"                ],
       #['/hwlcd/PanelEntry/AcmLutSataTable',               \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-acm-lut-sata-table = <",             ">;\n"                ],
       #['/hwlcd/PanelEntry/AcmLutSatrTable' ,              \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-acm-lut-satr-table = <",             ">;\n"                ],
       #['/hwlcd/PanelEntry/GammaLutTableR',                \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-gamma-lut-table-r = <",              ">;\n"                ],
       #['/hwlcd/PanelEntry/GammaLutTableG',                \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-gamma-lut-table-g = <",              ">;\n"                ],
       #['/hwlcd/PanelEntry/GammaLutTableB',                \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-gamma-lut-table-b = <",              ">;\n"                ],
       #['/hwlcd/PanelEntry/IgmLutTableR',                  \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-igm-lut-table-r = <",                ">;\n"                ],
       #['/hwlcd/PanelEntry/IgmLutTableG',                  \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-igm-lut-table-g = <",                ">;\n"                ],
       #['/hwlcd/PanelEntry/IgmLutTableB',                  \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-igm-lut-table-b = <",                ">;\n"                ],
       #['/hwlcd/PanelEntry/GmpLutTableLow32bit',           \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-gmp-lut-table-low32bit = <",         ">;\n"                ],
       #['/hwlcd/PanelEntry/GmpLutTableHigh4bit',           \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-gmp-lut-table-high4bit = <",         ">;\n"                ],
       #['/hwlcd/PanelEntry/XccTable',                      \&parse_multi_xml,
       #'need_nothing_here',                                "-n",        'hisi',
       #"\t\thw,lcdkit-xcc-table = <",                      ">;\n"                ],

        #the parameter of product
        ['/hwlcd/PanelEntry/HBackPorch',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-h-back-porch = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/HFrontPorch',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-h-front-porch = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/HPulseWidth',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-h-pulse-width = <",                  ">;\n"                ],      
        ['/hwlcd/PanelEntry/VBackPorch',                    \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-v-back-porch = <",                   ">;\n"                ],
        ['/hwlcd/PanelEntry/VPulseWidth',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-v-pulse-width = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/VFrontPorch',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-v-front-porch = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/HSyncSkew',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-h-sync-skew = <",                    ">;\n"                ],

        ['/hwlcd/PanelEntry/LcdType',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcd-type = <",                       ">;\n"                ],

        ['/hwlcd/PanelEntry/PanelPtTestSupport',            \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-pt-test-support = <",          ">;\n"                ],
        ['/hwlcd/PanelEntry/PanelHkadcSupport',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-hkadc-support = <",            ">;\n"                ],

        ['/hwlcd/PanelEntry/BiasPowerCtrlMode',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-bias-power-ctrl-mode = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/IovccPowerCtrlMode',            \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-iovcc-power-ctrl-mode = <",          ">;\n"                ],
        ['/hwlcd/PanelEntry/VciPowerCtrlMode',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-vci-power-ctrl-mode = <",            ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioId0',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-id0-gpio = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioId1',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-id1-gpio = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioReset',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-reset-gpio = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioTe',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-te-gpio = <",                        ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioVsp',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-vsp-gpio = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioVsn',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-vsn-gpio = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioIovcc',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-iovcc-gpio = <",                     ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioVci',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-vci-gpio = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/GpioBl',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-bl-gpio = <",                        ">;\n"                ],

        ['/hwlcd/PanelEntry/IovccOnIsNeedReset',            \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-iovcc-on-is-need-reset = <",         ">;\n"                ],
        ['/hwlcd/PanelEntry/VsnOnIsNeedReset',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-vsn-on-is-need-reset = <",           ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdanalogVcc',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcdanalog-vcc = <",                  ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdioVcc',                      \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcdio-vcc = <",                      ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdBias',                       \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcd-bias = <",                       ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdVsp',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcd-vsp = <",                        ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdVsn',                        \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcd-vsn = <",                        ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdRstFirstHigh',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcd-rst-first-high = <",             ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdRstLow',                     \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcd-rst-low = <",                    ">;\n"                ],
        ['/hwlcd/PanelEntry/LcdRstSecondHigh',              \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-lcd-rst-second-high = <",            ">;\n"                ],

        ['/hwlcd/PanelEntry/DelayAfVciOn',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-vci-on = <",                ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfIovccOn',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-iovcc-on = <",              ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfBiasOn',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-bias-on = <",               ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfVspOn',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-vsp-on = <",                ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfVsnOn',                  \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-vsn-on = <",                ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfLp11',                   \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-lp11 = <",                  ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfTpReset',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-tp-reset = <",              ">;\n"                ],

        ['/hwlcd/PanelEntry/DelayAfVsnOff',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-vsn-off = <",               ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfVspOff',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-vsp-off = <",               ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfBiasOff',                \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-bias-off = <",              ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfIovccOff',               \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-iovcc-off = <",             ">;\n"                ], 
        ['/hwlcd/PanelEntry/DelayAfVciOff',                 \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-delay-af-vci-off = <",               ">;\n"                ], 
        ['/hwlcd/PanelEntry/PanelOffResetHigh',             \&parse_multi_xml,
        'need_nothing_here',                                "-n",        'comm',
        "\t\thw,lcdkit-panel-off-reset-high = <",           ">;\n"                ], 
        );

for ($count = 0; $count < @dtsi_property_strings; $count++){
    if (($platform ne $dtsi_property_strings[$count][4])
     && ('comm' ne $dtsi_property_strings[$count][4]))
    {
        next;
    }
    
    if ($dtsi_property_strings[$count][0] eq 'need_nothing_here'){
        print $panel_dtsi_file $dtsi_property_strings[$count][5];
        next;
    }

    if ($dtsi_property_strings[$count][0] eq 'depond-on')
    {
        my $parser_tmp_str = $dtsi_property_strings[$count][1]->($dtsi_property_strings[$count][2]);
        if ($parser_tmp_str ne $parse_error_string){
            print $panel_dtsi_file $dtsi_property_strings[$count][5];
        }
        next;
    }

    my $parser_tmp_str = $dtsi_property_strings[$count][1]->($dtsi_property_strings[$count][0]);
    if ($parser_tmp_str eq $parse_error_string)    {
        debug_print("parse $dtsi_property_strings[$count][0] get a error string!\n");
        next;
    }

    if ($dtsi_property_strings[$count][3] eq '-f')    {
        $parser_tmp_str = $dtsi_property_strings[$count][2]->($parser_tmp_str);
        if ($parser_tmp_str eq $parse_error_string)    {
            debug_print("parse $dtsi_property_strings[$count][0] string trans error!\n");
            next;
        }
    }
    
    if ($dtsi_property_strings[$count][3] eq "eq")    {
        if ($parser_tmp_str ne $dtsi_property_strings[$count][2])    {
            next;
        }
        
        $parser_tmp_str = '';
    }
    
    if ($dtsi_property_strings[$count][3] eq "ne")    {
        if ($parser_tmp_str eq $dtsi_property_strings[$count][2])    {
            next;
        }
        
        $parser_tmp_str = '';
    }

    $parser_tmp_str = $dtsi_property_strings[$count][5].$parser_tmp_str.$dtsi_property_strings[$count][6];
    print $panel_dtsi_file $parser_tmp_str;
}

print $panel_dtsi_file create_dtsi_tail();

close($panel_dtsi_file);

exit_with_info($panel_file_name, 0);

sub parser_hex_order {  return parser_hex_order_base(shift, $platform);  }
sub parse_multi_xml  {  return parse_multi_xml_base(\@lcd_xml_doc, shift);  }
