#ifndef __BSP_SIMLOCK_H__
#define __BSP_SIMLOCK_H__

#define SIMLOCK_SECURITY_ERR_BASE  -20000

enum {
    SIMLOCK_SECURITY_CREATE_KEY_PARA_ERR = SIMLOCK_SECURITY_ERR_BASE,
    SIMLOCK_SECURITY_CREATE_KEY_ALLOC_ERR,
    SIMLOCK_SECURITY_CREATE_KEY_HUK_ZERO_ERR,
    SIMLOCK_SECURITY_CRYPTO_HASH_NULL_POINT_ERR,
    SIMLOCK_SECURITY_CRYPTO_HASH_PARA_ERR,
    SIMLOCK_SECURITY_CRYPTO_HASH_LENGTH_ERR,
    SIMLOCK_SECURITY_CRYPTO_HASH_TYPE_ERR,
    SIMLOCK_SECURITY_ENCRYPT_NULL_POINT_ERR,
    SIMLOCK_SECURITY_ENCRYPT_PARA_ERR,
    SIMLOCK_SECURITY_CRYPTO_HMAC_NULL_POINT_ERR,
    SIMLOCK_SECURITY_CRYPTO_HMAC_ALG_ERR,
    SIMLOCK_SECURITY_CRYPTO_HMAC_OUTLEN_ERR,
    SIMLOCK_SECURITY_CRYPTO_PBKDF2_NULL_POINT_ERR,
    SIMLOCK_SECURITY_CRYPTO_PBKDF2_ALG_ERR,
    SIMLOCK_SECURITY_CRYPTO_PBKDF2_INLEN_ERR,
    SIMLOCK_SECURITY_DECRYPT_NULL_POINT_ERR,
    SIMLOCK_SECURITY_DECRYPT_PARA_ERR,
    SIMLOCK_SECURITY_DECRYPT_AES_INIT_ERR,
    SIMLOCK_SECURITY_DECRYPT_AES_BLOCK_ERR,
    SIMLOCK_SECURITY_RSA_ENCRYPT_NULL_POINT_ERR,
    SIMLOCK_SECURITY_RSA_ENCRYPT_PARA_ERR,
    SIMLOCK_SECURITY_RSA_DECRYPT_NULL_POINT_ERR,
    SIMLOCK_SECURITY_RSA_DECRYPT_PARA_ERR,
    SIMLOCK_SECURITY_DECRYPT_PARAIV_ERR,
};

#endif

