#ifndef _GPT_PARTITION_TABLE_H_
#define _GPT_PARTITION_TABLE_H_

#include "bsp_partition.h"
#include "ptable_com.h"

/*!!!please not include this head file, except partition itself!!!*/

struct partition partition_table[MAX_PART_NUM] =
{
    /*name*/        				/*offset*/          			/*capacity*/   					/*flags*/
#if (PTABLE_M3_BOOT_LEN != 0)
    {PTABLE_M3BOOT_NM,				PTABLE_M3_BOOT_START, 			PTABLE_M3_BOOT_LEN,  			BOOT_PART},
#endif
#if (PTABLE_GPT_LEN != 0)
    {PTABLE_GPT_NM,       			PTABLE_GPT_START, 				PTABLE_GPT_LEN,  				USER_PART},
#endif
#if (PTABLE_FASTBOOT_LEN != 0)
    {PTABLE_FASTBOOT_NM,			PTABLE_FASTBOOT_START, 			PTABLE_FASTBOOT_LEN, 			USER_PART},
#endif
#if (PTABLE_NVFACTORY_LEN != 0)
    {PTABLE_NVDEFAULT_NM,			PTABLE_NVFACTORY_START, 		PTABLE_NVFACTORY_LEN,      		USER_PART},
#endif
#if (PTABLE_NV_LTE_LEN != 0)
    {PTABLE_NVBACK_NM,				PTABLE_NV_LTE_START, 			PTABLE_NV_LTE_LEN,      		USER_PART},
#endif
#if (PTABLE_NVIMG_LEN != 0)
    {PTABLE_NVIMG_NM,				PTABLE_NVIMG_START,				PTABLE_NVIMG_LEN,  				USER_PART},
#endif
#if (PTABLE_NVDLD_LEN != 0)
    {PTABLE_NVDLOAD_NM,				PTABLE_NVDLD_START,				PTABLE_NVDLD_LEN,  				USER_PART},
#endif
#if (PTABLE_SEC_STORAGE_LEN != 0)
    {PTABLE_SEC_STORAGE_NM,			PTABLE_SEC_STORAGE_START,		PTABLE_SEC_STORAGE_LEN,  		USER_PART},
#endif
#if (PTABLE_M3IMAGE_LEN != 0)
    {PTABLE_M3IMG_NM,				PTABLE_M3IMAGE_START,			PTABLE_M3IMAGE_LEN,				USER_PART},
#endif
#if (PTABLE_RECOVERY_A_LEN != 0)
    {PTABLE_RECOVERYA_NM,			PTABLE_RECOVERY_A_START,		PTABLE_RECOVERY_A_LEN, 			USER_PART},
#endif
#if (PTABLE_RECOVERY_B_LEN != 0)
    {PTABLE_RECOVERYB_NM,			PTABLE_RECOVERY_B_START,		PTABLE_RECOVERY_B_LEN,   		USER_PART},
#endif
#if (PTABLE_MISC_LEN != 0)
    {PTABLE_MISC_NM,				PTABLE_MISC_START,				PTABLE_MISC_LEN,  				USER_PART},
#endif
#if (PTABLE_DTS_LEN != 0)
    {PTABLE_DTS_NM,					PTABLE_DTS_START,				PTABLE_DTS_LEN,  				USER_PART},
#endif
#if (PTABLE_TEEOS_LEN != 0)
    {PTABLE_TEEOS_NM,				PTABLE_TEEOS_START,				PTABLE_TEEOS_LEN, 				USER_PART},
#endif
#if (PTABLE_BOOTIMAGE_LEN != 0)
    {PTABLE_KERNEL_NM,				PTABLE_BOOTIMAGE_START,			PTABLE_BOOTIMAGE_LEN, 			USER_PART},
#endif
#if (PTABLE_BOOTIMAGEBAK_LEN != 0)
    {PTABLE_KERNELBK_NM,			PTABLE_BOOTIMAGEBAK_START,		PTABLE_BOOTIMAGEBAK_LEN, 		USER_PART},
#endif
#if (PTABLE_MODEM_FW_LEN != 0)
        {PTABLE_MODEM_FW_NM,		PTABLE_MODEM_FW_START,			PTABLE_MODEM_FW_LEN, 			USER_PART},
#endif
#if (PTABLE_YAFFS_ONLINE_LEN != 0)
    {PTABLE_ONLINE_NM,				PTABLE_YAFFS_ONLINE_START,		PTABLE_YAFFS_ONLINE_LEN, 		USER_PART},
#endif
#if (PTABLE_HIFI_LEN != 0)
    {PTABLE_HIFI_NM,				PTABLE_HIFI_START,				PTABLE_HIFI_LEN,  				USER_PART},
#endif
#if (PTABLE_OEMINFO_LEN != 0)
    {PTABLE_OEMINFO_NM,				PTABLE_OEMINFO_START,			PTABLE_OEMINFO_LEN,  			USER_PART},
#endif
#if (PTABLE_RESERVE1_LEN != 0)
    {PTABLE_RESERVE1_NM,			PTABLE_RESERVE1_START,			PTABLE_RESERVE1_LEN, 			USER_PART},
#endif
#if (PTABLE_RESERVE2_LEN != 0)
    {PTABLE_RESERVE2_NM,			PTABLE_RESERVE2_START,			PTABLE_RESERVE2_LEN,  			USER_PART},
#endif
#if (PTABLE_RESERVE3_LEN != 0)
    {PTABLE_RESERVE3_NM,			PTABLE_RESERVE3_START,			PTABLE_RESERVE3_LEN,  			USER_PART},
#endif
#if (PTABLE_OM_LEN != 0)
    {PTABLE_OM_NM,					PTABLE_OM_START,				PTABLE_OM_LEN,   		  		USER_PART},
#endif
#if (PTABLE_YAFFS_APP_LEN != 0)
    {PTABLE_APP_NM,          		PTABLE_YAFFS_APP_START,			PTABLE_YAFFS_APP_LEN,   		USER_PART},
#endif
#if (PTABLE_YAFFS_WEBUI_LEN != 0)
    {PTABLE_WEBUI_NM,				PTABLE_YAFFS_WEBUI_START,		PTABLE_YAFFS_WEBUI_LEN,   		USER_PART},
#endif
#if (PTABLE_YAFFS_SYSIMG_LEN != 0)
    {PTABLE_SYSTEM_NM,				PTABLE_YAFFS_SYSIMG_START,		PTABLE_YAFFS_SYSIMG_LEN, 		USER_PART},
#endif
#if (PTABLE_YAFFS_USERDATA_LEN != 0)
    {PTABLE_USERDATA_NM,			PTABLE_YAFFS_USERDATA_START,	PTABLE_YAFFS_USERDATA_LEN,   	USER_PART},
#endif
#if (PTABLE_LOGO_LEN != 0)
    {PTABLE_LOGO_NM,				PTABLE_LOGO_START,				PTABLE_LOGO_LEN, 				USER_PART},
#endif
#if (PTABLE_CACHE_LEN != 0)
    {PTABLE_CACHE_NM,        		PTABLE_CACHE_START,				PTABLE_CACHE_LEN, 	 			USER_PART},
#endif
#if (PTABLE_MULTI_CARRIER_LEN != 0)
    {PTABLE_MULTI_CARRIER_NM,		PTABLE_MULTI_CARRIER_START,		PTABLE_MULTI_CARRIER_LEN,  		USER_PART},
#endif
#if (PTABLE_ISO_LEN != 0)
    {PTABLE_CDROMISO_NM,			PTABLE_ISO_START,				PTABLE_ISO_LEN,  				USER_PART},
#endif
    {PTABLE_END_STR,				0x00000000,						0x00000000  ,   				0x00000000}
};


#endif
