ccflags-y += -Idrivers/media/huawei/camera/sensor
ccflags-y += -Idrivers/media/huawei/camera
ccflags-y += -Idrivers/media/huawei/camera/csi
ccflags-y += -Idrivers/media/huawei/camera/platform

obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX298) += imx298.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX230) += imx230.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX179) += imx179.o

obj-$(CONFIG_HUAWEI_CAMERA_USE_OV8865) += ov8865.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX219) += imx219.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_HI843) += hi843.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX286DUAL) += imx286dual.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX286HYBIRD) += imx286hybird.o
obj-$(CONFIG_HUAWEI_CAMERA_USE_IMX386HYBIRD) += imx386hybird.o
