

/******************************************************************************

                  版权所有 (C), 2001-2016, 华为技术有限公司

 ******************************************************************************
  文 件 名   : errlog_cfg.c
  版 本 号   : 初稿
  作    者   : d00212987
  生成日期   : 2016年2月19日
  最近修改   :
  功能描述   : Errlog关联列表模块
  函数列表   :
  修改历史   :
  1.日    期   : 2016年2月19日
    作    者   : d00212987
    修改内容   : Errlo关联列表新增

******************************************************************************/
/*****************************************************************************
  1 头文件包含
*****************************************************************************/
#include "errlog_cfg.h"


/*lint -e767 修改人:d00212987;原因:Log打印 */
//#define    THIS_FILE_ID        PS_FILE_ID_ERRLOG_CFG_C
/*lint +e767 修改人:d00212987;*/

/*****************************************************************************
  2 全局变量声明
*****************************************************************************/

/* Warning：代码自动生成区域，不能手工改动 begin */

/* TODO: g_aulModemErrRept hash_value:90a066575669fa12d21e058da0947328 */

/* TODO: python search flag satrt */
int g_aulModem0ErrRept[][3]=
{
    /* GU ErrLog 上报相关 Item:17 */
    {FAULT_ID_GU_ERR_LOG_REPT, I0_WUEPS_PID_MMC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_WUEPS_PID_CC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_UEPS_PID_MTA, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_WUEPS_PID_USIM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_UEPS_PID_GAS, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, UEPS_PID_RRM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_UEPS_PID_SN, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_WUEPS_PID_WRR, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I0_DSP_PID_APM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, PS_PID_IMSA, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, MSP_PID_DIAG_AGENT, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, PS_PID_ERRC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, TPS_PID_RRC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, PS_PID_MM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, TPS_PID_MAC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, PS_PID_MAC_UL, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, TLPHY_PID_RTTAGENT, 0},


    /* 注册失败 Item:19 */
    {FAULT_ID_1X_REG_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_REG_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_REG_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_MEASURE_INFO},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 语音质量差 Item:2 */
    {FAULT_ID_1X_VOICE_QUALITY_BAD, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_VOICE_QUALITY_BAD, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},

    /* 通用异常收集 Item:6 */
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_TCA_RCV_FAIL},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CL_MULTI_RESEL},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_PERSONALTY_COUNT_INVALID},

    /* 短息接收失败 Item:22 */
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 短息发送失败 Item:23 */
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I0_UEPS_PID_XSMS, NAS_ERR_LOG_ALM_XSMS_SND_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 电信VOLTE下， ims<->1x乒乓切换主动上报 Item:2 */
    {FAULT_ID_VOLTE_IMS_1X_SWITCH, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_VOLTE_IMS_1X_SWITCH, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},

    /* QPCH能力指示 Item:2 */
    {FAULT_ID_1X_QPCH_CHANGE, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_QPCH_SUPPORT},
    {FAULT_ID_1X_QPCH_CHANGE, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},

    /* PS会话异常 Item:16 */
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HSM, NAS_ERR_LOG_ALM_HRPD_SESSION_CLOSE_PROT_NEG_ERR},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS呼叫失败 Item:19 */
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I0_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_CALL_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS断链 Item:18 */
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I0_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_DISC_EXCEPTION},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* CSDR 1X主动上报统计数据 Item:1 */
    {FAULT_ID_1X_COUNT_DATA_REPORT, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_COUNT_DATA_ALARM_ID},

    /* CL模式下长时间不回4G Item:8 */
    {FAULT_ID_CL_LEAVE_LTE, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LEAVE_LTE_INFO},
    {FAULT_ID_CL_LEAVE_LTE, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_CL_LEAVE_LTE, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_CL_LEAVE_LTE, I0_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_QUICK_BACK_TO_4G_STATISTIC_INFO},
    {FAULT_ID_CL_LEAVE_LTE, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_CL_LEAVE_LTE, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_CL_LEAVE_LTE, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_C2L_BSR_FAIL},
    {FAULT_ID_CL_LEAVE_LTE, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},

    /* CL模式下HRPD或LTE丢网Item:18 */
    {FAULT_ID_HRPD_OR_LTE_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_DO_LTE_OOS_PROCESS_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_SLAVE_MEAS_INFO},

    /* CL模式下HRPD或LTE掉网恢复 Item:6 */
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, UEPS_PID_HSD, NAS_ERR_LOG_ALM_HRPD_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I0_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_QUICK_BACK_TO_4G_STATISTIC_INFO},

    /* CL多模搜网过程 Item:6 */
    {FAULT_ID_CL_OOS_SEARCH, I0_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_CL_OOS_SEARCH, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},

    /* AP定时查询触发物理层主动上报 Item:1 */
    {FAULT_ID_AP_GET_PHY_COUNT_DATA_REQ, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},

    /* 1x主叫失败 Item:24 */
    {FAULT_ID_1X_MO_CALL_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, I0_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_MO_CALL_EXCEPTION},
    {FAULT_ID_1X_MO_CALL_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_MO_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 1x掉网恢复 Item:3 */
    {FAULT_ID_1X_OOS_RECOVERY, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS_RECOVERY, UEPS_PID_XSD, NAS_ERR_LOG_ALM_1X_OOS_SEARCH},
    {FAULT_ID_1X_OOS_RECOVERY, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},

    /* 1x掉网 Item:15 */
    {FAULT_ID_1X_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_OOS, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_OOS_PROCESS_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_SYNC_FAIL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x掉话 Item:18 */
    {FAULT_ID_1X_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, I0_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_CONVERSATION_EXCEPTION},
    {FAULT_ID_1X_CALL_EXCEPTION, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_CALL_DROP},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_TCH_HANDOFF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 1x被叫失败 Item:22 */
    {FAULT_ID_1X_MT_CALL_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, I0_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_MT_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},


};

int g_aulModem1ErrRept[][3]=
{
    /* GU ErrLog 上报相关 Item:9 */
    {FAULT_ID_GU_ERR_LOG_REPT, I1_WUEPS_PID_MMC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_WUEPS_PID_CC, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_UEPS_PID_MTA, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_WUEPS_PID_USIM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_UEPS_PID_GAS, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, UEPS_PID_RRM, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_UEPS_PID_SN, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_WUEPS_PID_WRR, 0},
    {FAULT_ID_GU_ERR_LOG_REPT, I1_DSP_PID_APM, 0},


    /* 注册失败 Item:19 */
    {FAULT_ID_1X_REG_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_REG_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_REG_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_REG_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_MEASURE_INFO},
    {FAULT_ID_1X_REG_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 语音质量差 Item:2 */
    {FAULT_ID_1X_VOICE_QUALITY_BAD, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_VOICE_QUALITY_BAD, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},

    /* 通用异常收集 Item:6 */
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_TCA_RCV_FAIL},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CL_MULTI_RESEL},
    {FAULT_ID_HRPD_EXCEPTION_COLLECTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_PERSONALTY_COUNT_INVALID},

    /* 短息接收失败 Item:22 */
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_SHORT_MSG_RCV_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 短息发送失败 Item:23 */
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, I1_UEPS_PID_XSMS, NAS_ERR_LOG_ALM_XSMS_SND_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_SHORT_MSG_SEND_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 电信VOLTE下， ims<->1x乒乓切换主动上报 Item:2 */
    {FAULT_ID_VOLTE_IMS_1X_SWITCH, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_VOLTE_IMS_1X_SWITCH, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},

    /* QPCH能力指示 Item:2 */
    {FAULT_ID_1X_QPCH_CHANGE, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_QPCH_SUPPORT},
    {FAULT_ID_1X_QPCH_CHANGE, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},

    /* PS会话异常 Item:16 */
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HSM, NAS_ERR_LOG_ALM_HRPD_SESSION_CLOSE_PROT_NEG_ERR},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_SESSION_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS呼叫失败 Item:19 */
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I1_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_CALL_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_CALL_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* PS断链 Item:18 */
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I1_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_CDMA_PS_DISC_EXCEPTION},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CTTF_PID_HRPD_RMAC, CTTF_ERR_LOG_ALM_ID_HRPD},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, MSPS_PID_PPPC, PPP_ERR_LOG_ALM_ID_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_CONN_OPEN_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_SESSION_NEG_FAIL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_HRPD_PS_DISC_EXCEPTION, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},

    /* CSDR 1X主动上报统计数据 Item:1 */
    {FAULT_ID_1X_COUNT_DATA_REPORT, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_COUNT_DATA_ALARM_ID},

    /* CL模式下长时间不回4G Item:8 */
    {FAULT_ID_CL_LEAVE_LTE, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LEAVE_LTE_INFO},
    {FAULT_ID_CL_LEAVE_LTE, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_CL_LEAVE_LTE, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_CL_LEAVE_LTE, I1_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_QUICK_BACK_TO_4G_STATISTIC_INFO},
    {FAULT_ID_CL_LEAVE_LTE, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_CL_LEAVE_LTE, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_CL_LEAVE_LTE, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_C2L_BSR_FAIL},
    {FAULT_ID_CL_LEAVE_LTE, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},

    /* CL模式下HRPD或LTE丢网Item:18 */
    {FAULT_ID_HRPD_OR_LTE_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_CODEC_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_DO_LTE_OOS_PROCESS_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_LOST},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_NETWORK_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_HRPD_OR_LTE_OOS, CPROC_PID_HRPD_CM, CPROC_HRPD_ERR_LOG_SLAVE_MEAS_INFO},

    /* CL模式下HRPD或LTE掉网恢复 Item:6 */
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, UEPS_PID_HSD, NAS_ERR_LOG_ALM_HRPD_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_HRPD_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_CL_LTE_COMMON_INFO},
    {FAULT_ID_HRPD_OR_LTE_OOS_RECOVERY, I1_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_QUICK_BACK_TO_4G_STATISTIC_INFO},

    /* CL多模搜网过程 Item:6 */
    {FAULT_ID_CL_OOS_SEARCH, I1_UEPS_PID_MSCC, NAS_ERR_LOG_ALM_CL_OOS_SEARCH},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_RESEL_TO_LTE_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_RESEL_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_L2C_REDIRECT_FAIL},
    {FAULT_ID_CL_OOS_SEARCH, UEPS_PID_HALMP, ID_CAS_HRPD_ERR_LOG_COMMON_INFO},
    {FAULT_ID_CL_OOS_SEARCH, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_EVDO_ALARM_ID},

    /* AP定时查询触发物理层主动上报 Item:1 */
    {FAULT_ID_AP_GET_PHY_COUNT_DATA_REQ, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},

    /* 1x主叫失败 Item:24 */
    {FAULT_ID_1X_MO_CALL_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, I1_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_MO_CALL_EXCEPTION},
    {FAULT_ID_1X_MO_CALL_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MO_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_MO_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_MO_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 1x掉网恢复 Item:3 */
    {FAULT_ID_1X_OOS_RECOVERY, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS_RECOVERY, UEPS_PID_XSD, NAS_ERR_LOG_ALM_1X_OOS_SEARCH},
    {FAULT_ID_1X_OOS_RECOVERY, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},

    /* 1x掉网 Item:15 */
    {FAULT_ID_1X_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_OOS, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_OOS_PROCESS_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_SYNC_FAIL},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_OOS, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_OOS, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PILOT_SEARCH_FAIL},
    {FAULT_ID_1X_OOS, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},

    /* 1x掉话 Item:18 */
    {FAULT_ID_1X_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, I1_WUEPS_PID_TAF, NAS_ERR_LOG_ALM_1X_CS_CONVERSATION_EXCEPTION},
    {FAULT_ID_1X_CALL_EXCEPTION, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_CALL_DROP},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_TCH_HANDOFF_FAIL},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_CALL_EXCEPTION, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_CALL_EXCEPTION, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},
    {FAULT_ID_1X_CALL_EXCEPTION, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_QPCH_ABNORMAL},

    /* 1x被叫失败 Item:22 */
    {FAULT_ID_1X_MT_CALL_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, I1_WUEPS_PID_MMA, NAS_ERR_LOG_ALM_1X_CODEC_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, MSPS_PID_1X_RMAC, CTTF_ERR_LOG_ALM_ID_1X},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_RRM, RRM_ERR_LOG_ALM_ID_CDMA_RPT_RESOURCE_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_ABNORMAL_REL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_EST_CNF_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_SYS_DETERMIN},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_REJECT},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_DECODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_NEGOTIATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_MULTI_HANDOFF},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_AUTHENTICATION_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_HANDOFF_FAIL_REVERT},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_OTA_ENCODE_FAIL},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_COMMON_INFO},
    {FAULT_ID_1X_MT_CALL_FAIL, UEPS_PID_1XCASM, ID_CAS_1X_ERR_LOG_ALARM_PSEUDO_CELL},
    {FAULT_ID_1X_MT_CALL_FAIL, PID_UPHY_CHR_AGENT, UPHY_CHR_ERRLOG_1X_ALARM_ID},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_NO_RESOURCE},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_FSM_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TIME_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_TCH_ABNORMAL},
    {FAULT_ID_1X_MT_CALL_FAIL, CPROC_PID_1X_CM, CPROC_1X_ERR_LOG_PAGING_RESULT},


};

/* TODO: python search flag end */
/* Warning：代码自动生成区域，不能手工改动 end */

/*****************************************************************************
  3 函数申明
*****************************************************************************/

/*****************************************************************************
 函 数 名  : ErrLog_GetErrReptAddrAndSize
 功能描述  : 获取Errlog全局变量地址
 输入参数  : ulModemId 主modem/副modem的id

 输出参数  : pulErrLogAddr
             pulsize

 返 回 值  : 0：success  其他：fail
 调用函数  :
 被调函数  :

 修改历史      :
  1.日    期   : 2016年02月19日
    作    者   : d00212987
    修改内容   :  ERR LOG FAULT ID关联项目新增
*****************************************************************************/
VOS_INT32 ErrLog_GetErrReptAddrAndSize(
    VOS_UINT32                           ulModemId,
    VOS_UINT_PTR                        *pulErrLogAddr,
    VOS_UINT32                          *pulsize
)
{
    if (MODEM_ID_0 == ulModemId)
    {
        *pulErrLogAddr = (VOS_UINT_PTR)g_aulModem0ErrRept;
        *pulsize = sizeof(g_aulModem0ErrRept);
    }
    else if (MODEM_ID_1 == ulModemId)
    {
        *pulErrLogAddr = (VOS_UINT_PTR)g_aulModem1ErrRept;
        *pulsize = sizeof(g_aulModem1ErrRept);

    }
    else
    {
        return VOS_ERR;
    }

    return VOS_OK;


}

/*****************************************************************************
 函 数 名  : ErrLog_GetPidAndAlarmId
 功能描述  : ulFaultId关联的pid/alarm_id查询接口
 输入参数  : ulModemId 主modem/副modem的id
             ulFaultId fault id

 输出参数  : paustAlarmArray fault id相关联的pid alarm_id数组，内存空间由diag_om提供，最大长度2048，支持一个faultid关联256个alarm_id；
             pulAlarmNum     fault id相关联的pid alarm_id数组成员个数，最大256；

 返 回 值  : 0：success  其他：fail
 调用函数  :
 被调函数  :

 修改历史      :
  1.日    期   : 2016年02月19日
    作    者   : d00212987
    修改内容   : ERR LOG FAULT ID关联项目新增
*****************************************************************************/
VOS_INT32 ErrLog_GetPidAndAlarmId(
    VOS_UINT32                          ulModemId,
    VOS_UINT32                          ulFaultId,
    ERR_LOG_ALARM_STRU                 *paustAlarmArray,
    VOS_UINT32                         *pulAlarmNum
)
{
    VOS_UINT_PTR                        ulErrLogAddr = VOS_NULL;
    VOS_UINT32                          ulsize;
    VOS_UINT32                          ulCount = 0;
    VOS_UINT32                          i;
    VOS_UINT32                          (*pulErrLogArry)[3];

    if (VOS_NULL_PTR == paustAlarmArray)
    {
        return VOS_ERR;
    }

    if (VOS_OK != ErrLog_GetErrReptAddrAndSize(ulModemId, &ulErrLogAddr, &ulsize))
    {
        return VOS_ERR;
    }

    pulErrLogArry = (VOS_UINT32(*)[])ulErrLogAddr;

    for (i=0; i < (ulsize / (3 * sizeof(VOS_UINT32))); i++)
    {
        if (ulFaultId == pulErrLogArry[i][0])
        {
            if (FAULT_ID_CONTAIN_ALARM_ID_MAX_NUM <= ulCount)
            {
                return VOS_ERR;
            }

            paustAlarmArray[ulCount].ulPid      = pulErrLogArry[i][1];
            paustAlarmArray[ulCount].ulAlarmID  = pulErrLogArry[i][2];
            ulCount++;
        }
    }

    *pulAlarmNum = ulCount;

    return VOS_OK;
}

/*****************************************************************************
 函 数 名  : ErrLog_IsContainPID
 功能描述  : 检查PID是否已经存在
 输入参数  : PID数组已及大小

 输出参数  : 是否存在

 返 回 值  : VOS_TRUE：存在  其他：VOS_FALSE
 调用函数  :
 被调函数  :

 修改历史      :
  1.日    期   : 2016年02月19日
    作    者   : d00212987
    修改内容   : ERR LOG FAULT ID关联项目新增
*****************************************************************************/
VOS_BOOL ErrLog_IsContainPID(
    VOS_UINT32                         *PaulPidArray,
    VOS_UINT32                          ulPidArrayLen,
    VOS_UINT32                          ulDstPid
)
{
    VOS_UINT32                          i;

    for (i=0; i < ulPidArrayLen; i++)
    {
        if (ulDstPid == PaulPidArray[i])
        {
            return VOS_TRUE;
        }
    }

    return VOS_FALSE;
}

/*****************************************************************************
 函 数 名  : ErrLog_GetErrlogPid
 功能描述  : 提供errlog相关的pid列表，用于errlog开关控制给各pid发送消息
 输入参数  : ulModemId 主modem/副modem的id

 输出参数  : PaulPidArray   errlog相关联的pid数组，内存空间由diag_om提供，最大长度1024，支持256个pid；
             pulPidNum      errlog相关联的pid数组成员个数，最大256；

 返 回 值  : 0：success  其他：fail
 调用函数  :
 被调函数  :

 修改历史      :
  1.日    期   : 2016年02月19日
    作    者   : d00212987
    修改内容   :  ERR LOG FAULT ID关联项目新增
*****************************************************************************/
VOS_INT32 ErrLog_GetErrlogPid(
    VOS_UINT32                          ulModemId,
    VOS_UINT32                         *PaulPidArray,
    VOS_UINT32                         *pulPidNum
)
{
    VOS_UINT_PTR                        ulErrLogAddr = VOS_NULL;
    VOS_UINT32                          ulsize;
    VOS_UINT32                          ulCount = 0;
    VOS_UINT32                          i;
    VOS_UINT32                          (*pulErrLogArry)[3];

    if (VOS_NULL_PTR == PaulPidArray)
    {
        return VOS_ERR;
    }

    if (VOS_OK != ErrLog_GetErrReptAddrAndSize(ulModemId, &ulErrLogAddr, &ulsize))
    {
        return VOS_ERR;
    }

    pulErrLogArry = (VOS_UINT32(*)[])ulErrLogAddr;

    for (i=0; i < (ulsize / (3 * sizeof(VOS_UINT32))); i++)
    {
        if (0 == i)
        {
            PaulPidArray[0] = pulErrLogArry[i][1];
            ulCount++;
            continue;
        }

        if (VOS_TRUE != ErrLog_IsContainPID(PaulPidArray, ulCount, pulErrLogArry[i][1]))
        {
            if (ERR_LOG_PID_MAX_NUM <= ulCount)
            {
                return VOS_ERR;
            }

            PaulPidArray[ulCount] = pulErrLogArry[i][1];
            ulCount++;
        }
    }

    *pulPidNum = ulCount;

    return VOS_OK;
}



