/*---------------------------------------------------------------------------
 * This file is autogenerated file using huawei LCD parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * Parser location: device/hisilicon/common/display/tools/huawei_lcd_panel 
 *---------------------------------------------------------------------------*/


#ifndef _HW_LCD_EXT_H_

#define _HW_LCD_EXT_H_


/*---------------------------------------------------------------------------*/
/* static lcd effect selection variable                                           */
/*---------------------------------------------------------------------------*/
enum {
AUO_ILI9885_5P5_1080P_VIDEO_PANEL,
AUO_NT35532_5P5_1080P_VIDEO_PANEL,
AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL,
AUO_TD4310_5P2_1080P_VIDEO_WAS_PANEL,
BOE_NT35532_5P5_1080P_VIDEO_PANEL,
BOE_NT35596_5P2_1080P_VIDEO_PANEL,
BOE_NT35596S_5P2_1080P_VIDEO_PANEL,
BOE_OTM1901A_5P2_1080P_VIDEO_PANEL,
BOE_OTM1906C_5P2_1080P_CMD_PANEL,
BOE_TD4300_5P2_1080P_VIDEO_PANEL,
EBBG_NT35596S_5P2_1080P_VIDEO_WAS_PANEL,
EBBG_NT35596S_5P2_1080P_VIDEO_PANEL,
EBBG_OTM1906C_5P2_1080P_CMD_PANEL,
INX_NT35532_5P5_1080P_VIDEO_PANEL,
INX_NT35596_5P2_1080P_VIDEO_PRA_PANEL,
INX_NT35596_5P2_1080P_VIDEO_PANEL,
INX_OTM1901A_5P2_1080P_VIDEO_PANEL,
JDI_NT35695_5P2_1080P_CMD_PANEL,
LG_R69006_5P2_1080P_CMD_PANEL,
TM_FT8716_5P2_1080P_VIDEO_PANEL,
TM_NT35596_5P2_1080P_VIDEO_PANEL,
TM_NT35596_5P5_1080P_VIDEO_PANEL,
TM_OTM1901A_5P2_1080P_VIDEO_PANEL,
TM_OTM1901A_5P5_1080P_VIDEO_PANEL,
TM_R63350_5P2_1080P_VIDEO_PANEL,
TM_R63350_5P5_1080P_VIDEO_PANEL,
};


/*---------------------------------------------------------------------------*/
/* static lcd mapping variable                                           */
/*---------------------------------------------------------------------------*/
struct hw_lcd_map {
	u32 lcd_id;
	char* panel_name;
};

static struct hw_lcd_map lcd_map[] = {
	{AUO_ILI9885_5P5_1080P_VIDEO_PANEL, "hisilicon,auo_ili9885_5p5_1080p_video"},
	{AUO_NT35532_5P5_1080P_VIDEO_PANEL, "hisilicon,auo_nt35532_5p5_1080p_video"},
	{AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL, "hisilicon,auo_otm1901a_5p2_1080p_video_default"},
	{AUO_TD4310_5P2_1080P_VIDEO_WAS_PANEL, "hisilicon,auo_td4310_5p2_1080p_video_was"},
	{BOE_NT35532_5P5_1080P_VIDEO_PANEL, "hisilicon,boe_nt35532_5p5_1080p_video"},
	{BOE_NT35596_5P2_1080P_VIDEO_PANEL, "hisilicon,boe_nt35596_5p2_1080p_video"},
	{BOE_NT35596S_5P2_1080P_VIDEO_PANEL, "hisilicon,boe_nt35596s_5p2_1080p_video"},
	{BOE_OTM1901A_5P2_1080P_VIDEO_PANEL, "hisilicon,boe_otm1901a_5p2_1080p_video"},
	{BOE_OTM1906C_5P2_1080P_CMD_PANEL, "hisilicon,boe_otm1906c_5p2_1080p_cmd"},
	{BOE_TD4300_5P2_1080P_VIDEO_PANEL, "hisilicon,boe_td4300_5p2_1080p_video"},
	{EBBG_NT35596S_5P2_1080P_VIDEO_WAS_PANEL, "hisilicon,ebbg_nt35596s_5p2_1080p_video_was"},
	{EBBG_NT35596S_5P2_1080P_VIDEO_PANEL, "hisilicon,ebbg_nt35596s_5p2_1080p_video"},
	{EBBG_OTM1906C_5P2_1080P_CMD_PANEL, "hisilicon,ebbg_otm1906c_5p2_1080p_cmd"},
	{INX_NT35532_5P5_1080P_VIDEO_PANEL, "hisilicon,inx_nt35532_5p5_1080p_video"},
	{INX_NT35596_5P2_1080P_VIDEO_PRA_PANEL, "hisilicon,inx_nt35596_5p2_1080p_video_pra"},
	{INX_NT35596_5P2_1080P_VIDEO_PANEL, "hisilicon,inx_nt35596_5p2_1080p_video"},
	{INX_OTM1901A_5P2_1080P_VIDEO_PANEL, "hisilicon,inx_otm1901a_5p2_1080p_video"},
	{JDI_NT35695_5P2_1080P_CMD_PANEL, "hisilicon,jdi_nt35695_5p2_1080p_cmd"},
	{LG_R69006_5P2_1080P_CMD_PANEL, "hisilicon,lg_r69006_5p2_1080p_cmd"},
	{TM_FT8716_5P2_1080P_VIDEO_PANEL, "hisilicon,tm_ft8716_5p2_1080p_video"},
	{TM_NT35596_5P2_1080P_VIDEO_PANEL, "hisilicon,tm_nt35596_5p2_1080p_video"},
	{TM_NT35596_5P5_1080P_VIDEO_PANEL, "hisilicon,tm_nt35596_5p5_1080p_video"},
	{TM_OTM1901A_5P2_1080P_VIDEO_PANEL, "hisilicon,tm_otm1901a_5p2_1080p_video"},
	{TM_OTM1901A_5P5_1080P_VIDEO_PANEL, "hisilicon,tm_otm1901a_5p5_1080p_video"},
	{TM_R63350_5P2_1080P_VIDEO_PANEL, "hisilicon,tm_r63350_5p2_1080p_video"},
	{TM_R63350_5P5_1080P_VIDEO_PANEL, "hisilicon,tm_r63350_5p5_1080p_video"},
};

static uint8_t hw_lcd_get_panel_id(char *name)
{
	uint8_t lcd_panel_id = AUO_OTM1901A_5P2_1080P_VIDEO_DEFAULT_PANEL; /*default panel id*/
	int i = 0;
	for (i = 0; i < ARRAY_SIZE(lcd_map); ++i) {
		if (0 == strncmp(name, lcd_map[i].panel_name, strlen(name))){		
			lcd_panel_id = lcd_map[i].lcd_id;
			break;
		}
	}

	return lcd_panel_id;
}

#endif /*_HW_LCD_EXT_H_*/
