#drivers/input/touchscreen
#
#Makefile for the touch driver of Focaltech
#obj-m += focaltech_ts.o
#focaltech_ts-objs := focaltech_core.o focaltech_flash.o focaltech_apk_node.o focaltech_dts.o focaltech_test.o

obj-$(CONFIG_FOCAL_TS_KIT) += focaltech_core.o
obj-$(CONFIG_FOCAL_TS_KIT) += focaltech_flash.o
obj-$(CONFIG_FOCAL_TS_KIT) += focaltech_apk_node.o
obj-$(CONFIG_FOCAL_TS_KIT) += focaltech_dts.o
obj-$(CONFIG_FOCAL_TS_KIT) += focaltech_test.o
